"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DocsIcon = exports.PlugInIcon = exports.BoxCubeIcon = exports.PieChartIcon = exports.PageIcon = exports.TableIcon = exports.ListIcon = exports.TaskIcon = exports.UserCircleIcon = exports.ChevronLeftIcon = exports.CopyIcon = exports.TimeIcon = exports.EyeCloseIcon = exports.EyeIcon = exports.CalenderIcon = exports.UserIcon = exports.LockIcon = exports.EnvelopeIcon = exports.PaperPlaneIcon = exports.ChevronDownIcon = exports.CloseLineIcon = exports.CheckLineIcon = exports.PencilIcon = exports.AngleDownIcon = exports.AngleUpIcon = exports.TrashBinIcon = exports.DollarLineIcon = exports.ShootingStarIcon = exports.BoxIconLine = exports.GroupIcon = exports.ArrowRightIcon = exports.ArrowDownIcon = exports.FolderIcon = exports.ArrowUpIcon = exports.ErrorIcon = exports.InfoIcon = exports.AlertIcon = exports.CheckCircleIcon = exports.CloseIcon = exports.BoxIcon = exports.PlusIcon = exports.BoltIcon = exports.VideoIcon = exports.AudioIcon = exports.GridIcon = exports.FileIcon = exports.DownloadIcon = exports.MoreDotIcon = exports.AlertHexaIcon = exports.ErrorHexaIcon = void 0;
exports.AngleRightIcon = exports.AngleLeftIcon = exports.ChatIcon = exports.ChevronUpIcon = exports.HorizontaLDots = exports.MailIcon = void 0;
var plus_svg_react_1 = require("./plus.svg?react");
Object.defineProperty(exports, "PlusIcon", { enumerable: true, get: function () { return plus_svg_react_1.ReactComponent; } });
var close_svg_react_1 = require("./close.svg?react");
Object.defineProperty(exports, "CloseIcon", { enumerable: true, get: function () { return close_svg_react_1.ReactComponent; } });
var box_svg_react_1 = require("./box.svg?react");
Object.defineProperty(exports, "BoxIcon", { enumerable: true, get: function () { return box_svg_react_1.ReactComponent; } });
var check_circle_svg_react_1 = require("./check-circle.svg?react");
Object.defineProperty(exports, "CheckCircleIcon", { enumerable: true, get: function () { return check_circle_svg_react_1.ReactComponent; } });
var alert_svg_react_1 = require("./alert.svg?react");
Object.defineProperty(exports, "AlertIcon", { enumerable: true, get: function () { return alert_svg_react_1.ReactComponent; } });
var info_svg_react_1 = require("./info.svg?react");
Object.defineProperty(exports, "InfoIcon", { enumerable: true, get: function () { return info_svg_react_1.ReactComponent; } });
var info_error_svg_react_1 = require("./info-error.svg?react");
Object.defineProperty(exports, "ErrorIcon", { enumerable: true, get: function () { return info_error_svg_react_1.ReactComponent; } });
var bolt_svg_react_1 = require("./bolt.svg?react");
Object.defineProperty(exports, "BoltIcon", { enumerable: true, get: function () { return bolt_svg_react_1.ReactComponent; } });
var arrow_up_svg_react_1 = require("./arrow-up.svg?react");
Object.defineProperty(exports, "ArrowUpIcon", { enumerable: true, get: function () { return arrow_up_svg_react_1.ReactComponent; } });
var arrow_down_svg_react_1 = require("./arrow-down.svg?react");
Object.defineProperty(exports, "ArrowDownIcon", { enumerable: true, get: function () { return arrow_down_svg_react_1.ReactComponent; } });
var folder_svg_react_1 = require("./folder.svg?react");
Object.defineProperty(exports, "FolderIcon", { enumerable: true, get: function () { return folder_svg_react_1.ReactComponent; } });
var videos_svg_react_1 = require("./videos.svg?react");
Object.defineProperty(exports, "VideoIcon", { enumerable: true, get: function () { return videos_svg_react_1.ReactComponent; } });
var audio_svg_react_1 = require("./audio.svg?react");
Object.defineProperty(exports, "AudioIcon", { enumerable: true, get: function () { return audio_svg_react_1.ReactComponent; } });
var grid_svg_react_1 = require("./grid.svg?react");
Object.defineProperty(exports, "GridIcon", { enumerable: true, get: function () { return grid_svg_react_1.ReactComponent; } });
var file_svg_react_1 = require("./file.svg?react");
Object.defineProperty(exports, "FileIcon", { enumerable: true, get: function () { return file_svg_react_1.ReactComponent; } });
var download_svg_react_1 = require("./download.svg?react");
Object.defineProperty(exports, "DownloadIcon", { enumerable: true, get: function () { return download_svg_react_1.ReactComponent; } });
var arrow_right_svg_react_1 = require("./arrow-right.svg?react");
Object.defineProperty(exports, "ArrowRightIcon", { enumerable: true, get: function () { return arrow_right_svg_react_1.ReactComponent; } });
var group_svg_react_1 = require("./group.svg?react");
Object.defineProperty(exports, "GroupIcon", { enumerable: true, get: function () { return group_svg_react_1.ReactComponent; } });
var box_line_svg_react_1 = require("./box-line.svg?react");
Object.defineProperty(exports, "BoxIconLine", { enumerable: true, get: function () { return box_line_svg_react_1.ReactComponent; } });
var shooting_star_svg_react_1 = require("./shooting-star.svg?react");
Object.defineProperty(exports, "ShootingStarIcon", { enumerable: true, get: function () { return shooting_star_svg_react_1.ReactComponent; } });
var dollar_line_svg_react_1 = require("./dollar-line.svg?react");
Object.defineProperty(exports, "DollarLineIcon", { enumerable: true, get: function () { return dollar_line_svg_react_1.ReactComponent; } });
var trash_svg_react_1 = require("./trash.svg?react");
Object.defineProperty(exports, "TrashBinIcon", { enumerable: true, get: function () { return trash_svg_react_1.ReactComponent; } });
var angle_up_svg_react_1 = require("./angle-up.svg?react");
Object.defineProperty(exports, "AngleUpIcon", { enumerable: true, get: function () { return angle_up_svg_react_1.ReactComponent; } });
var angle_down_svg_react_1 = require("./angle-down.svg?react");
Object.defineProperty(exports, "AngleDownIcon", { enumerable: true, get: function () { return angle_down_svg_react_1.ReactComponent; } });
var angle_left_svg_react_1 = require("./angle-left.svg?react");
Object.defineProperty(exports, "AngleLeftIcon", { enumerable: true, get: function () { return angle_left_svg_react_1.ReactComponent; } });
var angle_right_svg_react_1 = require("./angle-right.svg?react");
Object.defineProperty(exports, "AngleRightIcon", { enumerable: true, get: function () { return angle_right_svg_react_1.ReactComponent; } });
var pencil_svg_react_1 = require("./pencil.svg?react");
Object.defineProperty(exports, "PencilIcon", { enumerable: true, get: function () { return pencil_svg_react_1.ReactComponent; } });
var check_line_svg_react_1 = require("./check-line.svg?react");
Object.defineProperty(exports, "CheckLineIcon", { enumerable: true, get: function () { return check_line_svg_react_1.ReactComponent; } });
var close_line_svg_react_1 = require("./close-line.svg?react");
Object.defineProperty(exports, "CloseLineIcon", { enumerable: true, get: function () { return close_line_svg_react_1.ReactComponent; } });
var chevron_down_svg_react_1 = require("./chevron-down.svg?react");
Object.defineProperty(exports, "ChevronDownIcon", { enumerable: true, get: function () { return chevron_down_svg_react_1.ReactComponent; } });
var chevron_up_svg_react_1 = require("./chevron-up.svg?react");
Object.defineProperty(exports, "ChevronUpIcon", { enumerable: true, get: function () { return chevron_up_svg_react_1.ReactComponent; } });
var paper_plane_svg_react_1 = require("./paper-plane.svg?react");
Object.defineProperty(exports, "PaperPlaneIcon", { enumerable: true, get: function () { return paper_plane_svg_react_1.ReactComponent; } });
var lock_svg_react_1 = require("./lock.svg?react");
Object.defineProperty(exports, "LockIcon", { enumerable: true, get: function () { return lock_svg_react_1.ReactComponent; } });
var envelope_svg_react_1 = require("./envelope.svg?react");
Object.defineProperty(exports, "EnvelopeIcon", { enumerable: true, get: function () { return envelope_svg_react_1.ReactComponent; } });
var user_line_svg_react_1 = require("./user-line.svg?react");
Object.defineProperty(exports, "UserIcon", { enumerable: true, get: function () { return user_line_svg_react_1.ReactComponent; } });
var calender_line_svg_react_1 = require("./calender-line.svg?react");
Object.defineProperty(exports, "CalenderIcon", { enumerable: true, get: function () { return calender_line_svg_react_1.ReactComponent; } });
var eye_svg_react_1 = require("./eye.svg?react");
Object.defineProperty(exports, "EyeIcon", { enumerable: true, get: function () { return eye_svg_react_1.ReactComponent; } });
var eye_close_svg_react_1 = require("./eye-close.svg?react");
Object.defineProperty(exports, "EyeCloseIcon", { enumerable: true, get: function () { return eye_close_svg_react_1.ReactComponent; } });
var time_svg_react_1 = require("./time.svg?react");
Object.defineProperty(exports, "TimeIcon", { enumerable: true, get: function () { return time_svg_react_1.ReactComponent; } });
var copy_svg_react_1 = require("./copy.svg?react");
Object.defineProperty(exports, "CopyIcon", { enumerable: true, get: function () { return copy_svg_react_1.ReactComponent; } });
var chevron_left_svg_react_1 = require("./chevron-left.svg?react");
Object.defineProperty(exports, "ChevronLeftIcon", { enumerable: true, get: function () { return chevron_left_svg_react_1.ReactComponent; } });
var user_circle_svg_react_1 = require("./user-circle.svg?react");
Object.defineProperty(exports, "UserCircleIcon", { enumerable: true, get: function () { return user_circle_svg_react_1.ReactComponent; } });
var task_icon_svg_react_1 = require("./task-icon.svg?react");
Object.defineProperty(exports, "TaskIcon", { enumerable: true, get: function () { return task_icon_svg_react_1.ReactComponent; } });
var list_svg_react_1 = require("./list.svg?react");
Object.defineProperty(exports, "ListIcon", { enumerable: true, get: function () { return list_svg_react_1.ReactComponent; } });
var table_svg_react_1 = require("./table.svg?react");
Object.defineProperty(exports, "TableIcon", { enumerable: true, get: function () { return table_svg_react_1.ReactComponent; } });
var page_svg_react_1 = require("./page.svg?react");
Object.defineProperty(exports, "PageIcon", { enumerable: true, get: function () { return page_svg_react_1.ReactComponent; } });
var pie_chart_svg_react_1 = require("./pie-chart.svg?react");
Object.defineProperty(exports, "PieChartIcon", { enumerable: true, get: function () { return pie_chart_svg_react_1.ReactComponent; } });
var box_cube_svg_react_1 = require("./box-cube.svg?react");
Object.defineProperty(exports, "BoxCubeIcon", { enumerable: true, get: function () { return box_cube_svg_react_1.ReactComponent; } });
var plug_in_svg_react_1 = require("./plug-in.svg?react");
Object.defineProperty(exports, "PlugInIcon", { enumerable: true, get: function () { return plug_in_svg_react_1.ReactComponent; } });
var docs_svg_react_1 = require("./docs.svg?react");
Object.defineProperty(exports, "DocsIcon", { enumerable: true, get: function () { return docs_svg_react_1.ReactComponent; } });
var mail_line_svg_react_1 = require("./mail-line.svg?react");
Object.defineProperty(exports, "MailIcon", { enumerable: true, get: function () { return mail_line_svg_react_1.ReactComponent; } });
var horizontal_dots_svg_react_1 = require("./horizontal-dots.svg?react");
Object.defineProperty(exports, "HorizontaLDots", { enumerable: true, get: function () { return horizontal_dots_svg_react_1.ReactComponent; } });
var chat_svg_react_1 = require("./chat.svg?react");
Object.defineProperty(exports, "ChatIcon", { enumerable: true, get: function () { return chat_svg_react_1.ReactComponent; } });
var moredot_svg_react_1 = require("./moredot.svg?react");
Object.defineProperty(exports, "MoreDotIcon", { enumerable: true, get: function () { return moredot_svg_react_1.ReactComponent; } });
var alert_hexa_svg_react_1 = require("./alert-hexa.svg?react");
Object.defineProperty(exports, "AlertHexaIcon", { enumerable: true, get: function () { return alert_hexa_svg_react_1.ReactComponent; } });
var info_hexa_svg_react_1 = require("./info-hexa.svg?react");
Object.defineProperty(exports, "ErrorHexaIcon", { enumerable: true, get: function () { return info_hexa_svg_react_1.ReactComponent; } });
