"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KycStatus = exports.KycRequirements = exports.KycProgress = exports.KycDocumentUpload = exports.KycModal = void 0;
var KycModal_1 = require("./KycModal");
Object.defineProperty(exports, "KycModal", { enumerable: true, get: function () { return KycModal_1.default; } });
var KycDocumentUpload_1 = require("./KycDocumentUpload");
Object.defineProperty(exports, "KycDocumentUpload", { enumerable: true, get: function () { return KycDocumentUpload_1.default; } });
var KycProgress_1 = require("./KycProgress");
Object.defineProperty(exports, "KycProgress", { enumerable: true, get: function () { return KycProgress_1.default; } });
var KycRequirements_1 = require("./KycRequirements");
Object.defineProperty(exports, "KycRequirements", { enumerable: true, get: function () { return KycRequirements_1.default; } });
var KycStatus_1 = require("./KycStatus");
Object.defineProperty(exports, "KycStatus", { enumerable: true, get: function () { return KycStatus_1.default; } });
