"use strict";
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.notificationEmailTemplates = void 0;
exports.generateNotificationEmail = generateNotificationEmail;
exports.formatEmailData = formatEmailData;
exports.notificationEmailTemplates = {
    PAYMENT_RECEIVED: function (data) { return ({
        subject: "\uD83D\uDCB0 Payment Received - $".concat(data.amount),
        html: "\n      <div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n        <div style=\"background: linear-gradient(135deg, #0d9488, #047857); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n          <h1 style=\"color: white; margin: 0; font-size: 24px;\">Payment Received!</h1>\n        </div>\n        <div style=\"padding: 30px; background: white; border-radius: 0 0 10px 10px; border: 1px solid #e5e7eb;\">\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Hello <strong>".concat(data.account_name, "</strong>,\n          </p>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            We're pleased to inform you that a payment of <strong>$").concat(data.amount, "</strong> has been \n            credited to your account from <strong>").concat(data.sender, "</strong>.\n          </p>\n          <div style=\"background: #f0fdfa; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #0d9488;\">\n            <p style=\"margin: 0; color: #374151;\">\n              <strong>Reference:</strong> ").concat(data.reference, "<br>\n              <strong>Date:</strong> ").concat(new Date(data.timestamp).toLocaleDateString(), "<br>\n              <strong>New Balance:</strong> $").concat(data.new_balance, "\n            </p>\n          </div>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            You can view this transaction in your dashboard anytime.\n          </p>\n          <a href=\"").concat(data.dashboard_url, "\" style=\"display: inline-block; background: #0d9488; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-top: 20px;\">\n            View in Dashboard\n          </a>\n          <p style=\"color: #6b7280; font-size: 14px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;\">\n            This is an automated notification from Claverica Financial System.<br>\n            If you have any questions, please contact our support team.\n          </p>\n        </div>\n      </div>\n    "),
        text: "\n      Payment Received - $".concat(data.amount, "\n      \n      Hello ").concat(data.account_name, ",\n      \n      We're pleased to inform you that a payment of $").concat(data.amount, " has been \n      credited to your account from ").concat(data.sender, ".\n      \n      Reference: ").concat(data.reference, "\n      Date: ").concat(new Date(data.timestamp).toLocaleDateString(), "\n      New Balance: $").concat(data.new_balance, "\n      \n      You can view this transaction in your dashboard anytime: ").concat(data.dashboard_url, "\n      \n      This is an automated notification from Claverica Financial System.\n      If you have any questions, please contact our support team.\n    ")
    }); },
    TAC_SENT: function (data) { return ({
        subject: '🔐 Your TAC Code for Transfer Authorization',
        html: "\n      <div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n        <div style=\"background: linear-gradient(135deg, #6366f1, #4f46e5); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n          <h1 style=\"color: white; margin: 0; font-size: 24px;\">Your TAC Code</h1>\n        </div>\n        <div style=\"padding: 30px; background: white; border-radius: 0 0 10px 10px; border: 1px solid #e5e7eb;\">\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Hello <strong>".concat(data.account_name, "</strong>,\n          </p>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Your Transaction Authorization Code (TAC) is:\n          </p>\n          <div style=\"text-align: center; margin: 30px 0;\">\n            <div style=\"display: inline-block; background: #f8fafc; padding: 20px 40px; border-radius: 8px; border: 2px dashed #6366f1;\">\n              <h2 style=\"color: #6366f1; font-size: 36px; letter-spacing: 10px; margin: 0;\">").concat(data.tac_code, "</h2>\n            </div>\n          </div>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            <strong>Purpose:</strong> ").concat(data.purpose, "<br>\n            <strong>Expires:</strong> ").concat(new Date(data.expires_at).toLocaleString(), "\n          </p>\n          <div style=\"background: #fef2f2; padding: 15px; border-radius: 6px; margin: 20px 0; border-left: 4px solid #dc2626;\">\n            <p style=\"margin: 0; color: #dc2626; font-size: 14px;\">\n              <strong>\u26A0\uFE0F SECURITY WARNING:</strong> Never share this code with anyone. \n              Claverica staff will never ask for your TAC code.\n            </p>\n          </div>\n          <p style=\"color: #6b7280; font-size: 14px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;\">\n            This TAC code is valid for 10 minutes only.<br>\n            If you didn't request this code, please contact support immediately.\n          </p>\n        </div>\n      </div>\n    "),
        text: "\n      Your TAC Code for Transfer Authorization\n      \n      Hello ".concat(data.account_name, ",\n      \n      Your Transaction Authorization Code (TAC) is: ").concat(data.tac_code, "\n      \n      Purpose: ").concat(data.purpose, "\n      Expires: ").concat(new Date(data.expires_at).toLocaleString(), "\n      \n      \u26A0\uFE0F SECURITY WARNING: Never share this code with anyone. \n      Claverica staff will never ask for your TAC code.\n      \n      This TAC code is valid for 10 minutes only.\n      If you didn't request this code, please contact support immediately.\n    ")
    }); },
    KYC_APPROVED: function (data) { return ({
        subject: '✅ Your KYC Verification is Complete',
        html: "\n      <div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n        <div style=\"background: linear-gradient(135deg, #10b981, #059669); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n          <h1 style=\"color: white; margin: 0; font-size: 24px;\">KYC Verification Approved!</h1>\n        </div>\n        <div style=\"padding: 30px; background: white; border-radius: 0 0 10px 10px; border: 1px solid #e5e7eb;\">\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Hello <strong>".concat(data.account_name, "</strong>,\n          </p>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            We're happy to inform you that your KYC (Know Your Customer) verification has been \n            successfully approved!\n          </p>\n          <div style=\"background: #d1fae5; padding: 20px; border-radius: 8px; margin: 20px 0; text-align: center;\">\n            <div style=\"background: white; width: 60px; height: 60px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; margin-bottom: 15px;\">\n              <span style=\"color: #10b981; font-size: 30px;\">\u2713</span>\n            </div>\n            <h3 style=\"color: #065f46; margin: 10px 0; font-size: 20px;\">Verification Complete</h3>\n            <p style=\"color: #065f46; margin: 0;\">\n              Your account is now fully verified and activated.\n            </p>\n          </div>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            With your verified account, you now have access to:\n          </p>\n          <ul style=\"color: #374151; font-size: 16px; line-height: 1.6; padding-left: 20px;\">\n            <li>Higher transaction limits</li>\n            <li>Full account features</li>\n            <li>Enhanced security options</li>\n            <li>Priority customer support</li>\n          </ul>\n          <a href=\"").concat(data.dashboard_url, "\" style=\"display: inline-block; background: #10b981; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-top: 20px;\">\n            Access Your Dashboard\n          </a>\n          <p style=\"color: #6b7280; font-size: 14px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;\">\n            Thank you for completing the verification process.<br>\n            Welcome to the Claverica community!\n          </p>\n        </div>\n      </div>\n    "),
        text: "\n      Your KYC Verification is Complete\n      \n      Hello ".concat(data.account_name, ",\n      \n      We're happy to inform you that your KYC (Know Your Customer) verification has been \n      successfully approved!\n      \n      Your account is now fully verified and activated.\n      \n      With your verified account, you now have access to:\n      \u2022 Higher transaction limits\n      \u2022 Full account features\n      \u2022 Enhanced security options\n      \u2022 Priority customer support\n      \n      Access your dashboard: ").concat(data.dashboard_url, "\n      \n      Thank you for completing the verification process.\n      Welcome to the Claverica community!\n    ")
    }); },
    TRANSFER_COMPLETED: function (data) { return ({
        subject: "\u2705 Transfer Completed - $".concat(data.amount),
        html: "\n      <div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;\">\n        <div style=\"background: linear-gradient(135deg, #8b5cf6, #7c3aed); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;\">\n          <h1 style=\"color: white; margin: 0; font-size: 24px;\">Transfer Completed!</h1>\n        </div>\n        <div style=\"padding: 30px; background: white; border-radius: 0 0 10px 10px; border: 1px solid #e5e7eb;\">\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Hello <strong>".concat(data.account_name, "</strong>,\n          </p>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            Your transfer of <strong>$").concat(data.amount, "</strong> has been successfully completed.\n          </p>\n          <div style=\"background: #f5f3ff; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #8b5cf6;\">\n            <p style=\"margin: 0; color: #374151;\">\n              <strong>To:</strong> ").concat(data.recipient_name, "<br>\n              <strong>Account:</strong> ").concat(data.recipient_account, "<br>\n              <strong>Reference:</strong> ").concat(data.reference, "<br>\n              <strong>Date:</strong> ").concat(new Date(data.timestamp).toLocaleDateString(), "<br>\n              <strong>Status:</strong> <span style=\"color: #10b981;\">Completed \u2713</span>\n            </p>\n          </div>\n          <p style=\"color: #374151; font-size: 16px; line-height: 1.6;\">\n            The funds have been sent to the recipient's account. It may take 1-2 business days \n            to appear in their account depending on their bank.\n          </p>\n          <a href=\"").concat(data.dashboard_url, "\" style=\"display: inline-block; background: #8b5cf6; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; font-weight: bold; margin-top: 20px;\">\n            View Transaction Details\n          </a>\n          <p style=\"color: #6b7280; font-size: 14px; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;\">\n            This is an automated confirmation of your completed transfer.<br>\n            A receipt has been saved to your transaction history.\n          </p>\n        </div>\n      </div>\n    "),
        text: "\n      Transfer Completed - $".concat(data.amount, "\n      \n      Hello ").concat(data.account_name, ",\n      \n      Your transfer of $").concat(data.amount, " has been successfully completed.\n      \n      To: ").concat(data.recipient_name, "\n      Account: ").concat(data.recipient_account, "\n      Reference: ").concat(data.reference, "\n      Date: ").concat(new Date(data.timestamp).toLocaleDateString(), "\n      Status: Completed \u2713\n      \n      The funds have been sent to the recipient's account. It may take 1-2 business days \n      to appear in their account depending on their bank.\n      \n      View transaction details: ").concat(data.dashboard_url, "\n      \n      This is an automated confirmation of your completed transfer.\n      A receipt has been saved to your transaction history.\n    ")
    }); },
};
// Helper function to generate email
function generateNotificationEmail(notificationType, data) {
    var template = exports.notificationEmailTemplates[notificationType];
    if (!template) {
        // Default template for unknown notification types
        return {
            subject: "Claverica: ".concat(data.title || 'Notification'),
            html: "\n        <div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;\">\n          <h2>".concat(data.title || 'Notification', "</h2>\n          <p>").concat(data.message || '', "</p>\n          ").concat(data.metadata ? "<pre style=\"background: #f5f5f5; padding: 10px; border-radius: 5px;\">".concat(JSON.stringify(data.metadata, null, 2), "</pre>") : '', "\n          <p style=\"color: #666; font-size: 12px; margin-top: 20px;\">\n            This is an automated email from Claverica Financial System.\n          </p>\n        </div>\n      "),
            text: "".concat(data.title || 'Notification', "\n\n").concat(data.message || '', "\n\n").concat(data.metadata ? JSON.stringify(data.metadata, null, 2) : '', "\n\nThis is an automated email from Claverica Financial System.")
        };
    }
    return template(data);
}
// Format email data with defaults
function formatEmailData(account, notification, baseUrl) {
    if (baseUrl === void 0) { baseUrl = 'http://localhost:3000'; }
    return __assign(__assign({ account_name: "".concat(account.first_name, " ").concat(account.last_name), account_number: account.account_number, dashboard_url: "".concat(baseUrl, "/dashboard") }, notification), (notification.metadata || {}));
}
